  version: '2'

  services:
    db:
      image: mariadb:10.3
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=1234qwer!
        - MYSQL_DATABASE=test_db
        - MYSQL_USER=test
        - MYSQL_PASSWORD=1234qwer!
      volumes:
        - ~/.mysql/data:/var/lib/mysql:rw
        - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql:rw
      command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=1']
